//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OV Grid DLL.rc
//
#define IDSAVE                          2
#define ID_UPDATE                       3
#define IDOK2                           3
#define ID_DEFAULT                      3
#define ID_VALIDATE_ISO                 4
#define IDCANCEL2                       4
#define IDOK3                           4
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_OVGRIDDLL_DIALOG            102
#define IDD_GRAPHPARAMDLG_DIALOG        103
#define IDD_PROPPAGE_LARGE1             107
#define IDR_MAINFRAME                   128
#define IDD_ISO_TABLE                   132
#define IDD_PROPPAGE_LARGE2             133
#define IDD_PROPPAGE_LARGE3             134
#define IDD_BASIC_2PHASE                138
#define IDD_BASIC_DLG                   139
#define IDD_GRAPHICS                    140
#define IDD_GRAPHICS_BLOCK              141
#define IDD_DIALOG1                     142
#define IDD_DIALOG_SIM_RUN              142
#define IDD_STAGE_DLG                   143
#define IDD_PROPPAGE_LARGE4             144
#define IDD_BLOCKERDLG_DIALOG           145
#define IDD_VISCODLG_DIALOG             146
#define IDD_PROPPAGE_LARGE5             147
#define IDD_ABOUTBOX                    148
#define IDD_PROPPAGE_LARGE6             149
#define IDD_FILEOPEN_DLG                150
#define IDD_DLG_OUTPUT_TIME             151
#define IDD_WARNINGS                    152
#define IDD_DIALOG_EDGE_CONC            153
#define IDB_BITMAP1                     154
#define IDD_MUTSOLV_DIALOG              155
#define IDD_CANA_DIALOG                 156
#define IDD_OPT                         157
#define IDD_DIALOG_ISOTHERM_FITTING     158
#define IDD_PROGRESS_BAR                159
#define IDD_DIALOG2                     160
#define IDD_CHECKLISTBOXCBN_DIALOG      161
#define IDD_CHECKLISTBOX_GRAPHS_DIALOG  162
#define IDD_IOSTHERM_DERIVATION_GRAPH_DIALOG 163
#define IDD_CHECKLISTBOX_GRAPHS_DIALOG1 164
#define IDR_MENU1                       165
#define IDS_BITMAP_NOT_CREATED_ERROR_MESSAGE 166
#define IDS_WINDOWS_BITMAP_FILES        167
#define IDD_OPTIMISATION_DLG            168
#define IDS_FILE_CREATE_ERROR_MESSAGE   169
#define IDD_PROPPAGE_LARGE7             170
#define IDD_DIA_ISO_PAR                 173
#define IDD_DIALOG_OPT_OUTPUT           174
#define IDR_MENU2                       175
#define IDD_DIALOG_ISO_PAR				176
#define IDC_READ_FILE                   1000
#define IDC_ADD_STAGE                   1001
#define IDC_STATIC_GRID                 1002
#define IDC_EDIT2                       1003
#define IDC_ABORT_RUN                   1004
#define IDC_EDIT_MAXCONC                1004
#define IDC_ISO_TABLE                   1005
#define IDC_STATIC_TABLE                1006
#define IDC_MOD                         1007
#define IDC_EDIT4                       1008
#define IDC_NUM_ROWS                    1009
#define IDC_UPDATE_ROWS                 1010
#define IDC_RADIAL                      1011
#define IDC_LINEAR                      1012
#define IDC_METRIC                      1013
#define IDC_ALL_LAYERS                  1014
#define IDC_STATIC_WATER_PROP           1015
#define IDC_STATIC_OIL_PROP             1016
#define IDC_GRAPH_CROSS2                1017
#define IDC_GRAPH_RAD                   1018
#define IDC_EDIT_MOD                    1019
#define IDC_NUM_BLOCKS                  1020
#define IDC_NUM_LAYERS                  1021
#define IDC_NUM_COMP                    1022
#define IDC_NUM_STAGES                  1023
#define IDC_UPDATE                      1024
#define IDC_STATIC_MU_WAT               1025
#define IDC_TOT_VOL                     1026
#define IDC_STATIC_MAX_RAD              1027
#define IDC_STATIC_MASS_TRANS           1028
#define IDC_CSHUT                       1029
#define IDC_CHECK_ALL_COMP              1030
#define IDC_STATIC_LAY_COND             1031
#define IDC_STATIC_COMP_COND            1032
#define IDC_CHECK_PIDF                  1034
#define IDC_CHECK_LAY_OPEN              1036
#define IDC_STATIC_FORMATION            1037
#define IDC_STATIC_WELLRAD              1038
#define IDC_STATIC_WAT_VISC             1039
#define IDC_STATIC_OIL_VISC             1040
#define IDC_STATIC_UNITS                1041
#define IDC_SLIDER_TIME_DELAY           1042
#define IDC_STATIC_ADDEDTIME            1043
#define IDC_EDIT_TITLE1                 1044
#define IDC_EDIT_TITLE2                 1045
#define IDC_GRAPH_TIME                  1046
#define IDC_EDIT_MODEL1                 1047
#define IDC_STATIC_ISOTHERM             1048
#define IDC_STATIC_VI                   1049
#define IDC_STATIC_TDV                  1050
#define IDC_STATIC_IHC                  1051
#define IDC_STATIC_RHO                  1052
#define IDC_STATIC_CSHUT                1053
#define IDC_SINGLE_PHASE                1054
#define IDC_TWO_PHASE                   1055
#define IDC_STATIC_SIM_TYPE             1056
#define IDC_CLOSE                       1057
#define IDC_NEW_STAGE_POS               1058
#define IDC_BASIC_PARA                  1059
#define IDC_RUN_MODEL                   1060
#define IDC_EDIT8                       1061
#define IDC_EDIT3                       1062
#define IDC_EDIT5                       1063
#define IDC_RADIO_INH                   1063
#define IDC_EDIT1                       1064
#define IDC_RC_WATVOL_LIN               1064
#define IDC_RADIO_EXTRAOUT              1064
#define IDC_CANCEL                      1065
#define IDC_RADIO_ADSORP                1065
#define IDC_EDIT_GENERATIONS            1065
#define IDC_REMOVE_STAGE                1066
#define IDC_RADIO_TEMPERATURE           1066
#define IDC_EDIT_TUBEROUGH              1066
#define IDC_EDIT_TRAINPER               1066
#define IDC_STATIC_STAGEGRID            1067
#define IDC_CHECK_MINMAXCON             1067
#define IDC_EDIT_FLUIDRHO               1067
#define IDC_STATIC_FLUID_PROP           1068
#define IDC_CHECK_GRAPH1                1068
#define IDC_EDIT_OILAPI                 1068
#define IDC_STATIC_ROCK_PROP            1069
#define IDC_CHECK_EXTRA_OUTPUT          1069
#define IDC_MASS_TRANSFER               1070
#define IDC_RADIO_ADSORP2               1070
#define IDC_RADIO_EXTRAOUT2             1070
#define IDC_CONVENTIONAL                1071
#define IDC_MASS_TRANSFER2              1072
#define IDC_BUTTON_GRAPHPARA            1072
#define IDC_ISOTHERM                    1073
#define IDC_CHECK_GRAPH2                1073
#define IDC_VOL_INJ                     1074
#define IDC_RC_TIME_LIN                 1074
#define IDC_CHECK_GRAPH3                1074
#define IDC_STATIC_MU_OIL               1075
#define IDC_RC_TIME_LOG                 1075
#define IDC_ISOTHERM2                   1075
#define IDC_ANAL_LINEAR                 1075
#define IDC_MASS_TRANS_EDIT             1076
#define IDC_RC_WATVOL_LOG               1076
#define IDC_ISOTHERM3                   1076
#define IDC_ISOTHERM_DER                1076
#define IDC_INH_CON                     1077
#define IDC_SCREEN_DISPLAY              1077
#define IDC_STATIC_WELL_RAD             1078
#define IDC_ISCON                       1078
#define IDC_RHO                         1079
#define IDC_ISTMP                       1079
#define IDC_CHECK_TIMESTEP              1080
#define IDC_RC_TIME                     1080
#define IDC_CHECK_HEADERS               1081
#define IDC_RC_WATPRO                   1081
#define IDC_STATIC_OLDFILES             1084
#define IDC_STATIC_NFREQ                1085
#define IDC_STATIC_NITERS               1086
#define IDC_STATIC_CLIFE1               1087
#define IDC_STATIC_CLIFE2               1088
#define IDC_STATIC_CLIFE3               1089
#define IDC_STATIC_CLIFE4               1090
#define IDC_STATIC_CLIFE5               1091
#define IDC_EDIT_GRAFMIC                1091
#define IDC_EDIT_MINCONC                1092
#define IDC_STATIC_GRAFMIC              1092
#define IDC_STATIC_GRAPH2               1093
#define IDC_STATIC_TOLITR               1094
#define IDC_STATIC_GRAPH3               1094
#define IDC_STATIC_FIELDTABLE           1095
#define IDC_SHOW_TABLE                  1096
#define IDC_STATIC_GRAPH1               1097
#define IDC_STATIC_FILENUM              1097
#define IDC_EDIT_NV                     1098
#define IDC_CHECK_WELLFRICTION          1098
#define IDC_INPUT_TABLE                 1098
#define IDC_EDIT_WAT_NV                 1098
#define IDC_STATIC_GRAPH4               1098
#define IDC_EDIT_N                      1099
#define IDC_STATIC_WELLDIA              1099
#define IDC_EDIT_WAT_N                  1099
#define IDC_REMOVE_TABLE                1099
#define IDC_EDIT_LANDA                  1100
#define IDC_STATIC_TUBEROUGH            1100
#define IDC_EDIT_WAT_LANDA              1100
#define IDC_STATIC_WATER_RF             1101
#define IDC_EDIT_WELLDIA                1101
#define IDC_EDIT_OIL_NV                 1101
#define IDC_STATIC_OIL_RF               1102
#define IDC_STATIC_FLUIDRHO             1102
#define IDC_EDIT_OIL_LANDA              1102
#define IDC_EDIT_MAXMU                  1103
#define IDC_STATIC_LAYER_SPACING        1103
#define IDC_EDIT_WAT_MAXMU              1103
#define IDC_EDIT_FORMTEMP               1104
#define IDC_EDIT_OIL_MAXMU              1104
#define IDC_REMOVE_FILENUM              1105
#define IDC_EDIT_AQHECAP                1105
#define IDC_EDIT_OIL_N                  1105
#define IDC_STATIC_RETCONC              1106
#define IDC_EDIT_FORMTHCOND             1106
#define IDC_STATIC_MAXITER              1107
#define IDC_EDIT_THCONDRES              1107
#define IDC_STATIC_MAXTIM               1108
#define IDC_STATIC_OILAPI               1108
#define IDC_STATIC_TOL                  1109
#define IDC_EDIT_AQPHDEN                1109
#define IDC_STATIC_RETPLOT              1110
#define IDC_EDIT_ROHECAP                1110
#define IDC_STATIC_GRPA                 1111
#define IDC_CHECK_TEMPERATURE           1111
#define IDC_BUTTON_STOP                 1112
#define IDC_INPUT_EFFLUENT              1112
#define IDC_BUTTON_PLAY                 1113
#define IDC_EDIT_AQPHDEN2               1113
#define IDC_CHECK_WAT_VISC              1113
#define IDC_BUTTON_HEADER               1114
#define IDC_BUTTON_BACK                 1114
#define IDC_CHECK_OIL_VISC              1114
#define IDC_STATIC_FORMTEMP             1115
#define IDC_BUTTON_PLAY2                1115
#define IDC_BUTTON_FOWARD               1115
#define IDC_STATIC_FORMTHCOND           1116
#define IDC_STATIC_THCONDRES            1117
#define IDC_STATIC_AQHECAP              1118
#define IDC_STATIC_ROGRDEN              1119
#define IDC_STATIC_AQPHDEN              1120
#define IDC_STATIC_ROHECAP              1121
#define IDC_SHOW_DATA                   1122
#define IDC_STATIC_ISOTABLE             1123
#define IDC_STATIC_ENTER0               1124
#define IDC_STATIC_NAHECAP              1124
#define IDC_STATIC_FIELDSQUEEZE         1125
#define IDC_STATIC_FILES                1126
#define IDC_EDIT_ROGRDEN                1127
#define IDC_RADIO_NK                    1127
#define IDC_RADIO_NCSE                  1128
#define IDC_RADIO_LIN                   1129
#define IDC_RADIO_LOG                   1130
#define IDC_STATIC_VOLINJ               1131
#define IDC_STATIC_VOLOVE               1132
#define IDC_STATIC_FN                   1134
#define IDC_STATIC_FK                   1135
#define IDC_STATIC_CSE                  1136
#define IDC_STATIC_MINVOL               1137
#define IDC_STATIC_MAXVOL               1138
#define IDC_STATIC_PHI                  1139
#define IDC_STATIC_CI                   1140
#define IDC_CHECK_SHEAR                 1140
#define IDC_CHECK_WAT_SHEAR             1140
#define IDC_STATIC_VOLINJE              1141
#define IDC_STATIC_LANDA                1141
#define IDC_STATIC_WAT_LANDA            1141
#define IDC_STATIC_VOLOVEE              1142
#define IDC_STATIC_N                    1142
#define IDC_STATIC_WAT_N                1142
#define IDC_STATIC_FNE                  1143
#define IDC_STATIC_OIL_LANDA            1143
#define IDC_BUTTON_HELP                 1143
#define IDC_STATIC_FKE                  1144
#define IDC_STATIC_OIL_N                1144
#define IDC_BUTTON_ABOUT                1144
#define IDC_STATIC_OUTPUTFILE           1144
#define IDC_STATIC_CSEE                 1145
#define IDC_CHECK_OIL_SHEAR             1145
#define IDC_CW                          1145
#define IDC_CO                          1146
#define IDC_STATIC_MINVOLE              1147
#define IDC_ADSW                        1147
#define IDC_STATIC_MAXVOLE              1148
#define IDC_ADSO                        1148
#define IDC_STATIC_NUMRET               1149
#define IDC_VISCW                       1149
#define IDC_EDIT_BLOCKMIC               1150
#define IDC_VISCO                       1150
#define IDC_RFW                         1151
#define IDC_RFO                         1152
#define IDC_CHECK_OUTPUTFILE            1153
#define IDC_SW                          1154
#define IDC_BUTTON_FILES                1154
#define IDC_FW                          1155
#define IDC_STATIC_FILE                 1155
#define IDC_CHECK_OUTPUTFILE2           1156
#define IDC_CHECK_WATER_TOTAL_FLOW      1159
#define IDC_CHECK_WATER_MASS            1160
#define IDC_WARNING                     1160
#define IDC_CHECK_WATER_FLOW_LAYER      1161
#define IDC_STATIC_KABS                 1161
#define IDC_CHECK_WATERCUT              1162
#define IDC_STATIC_SAT                  1162
#define IDC_CHECK_OIL_TOTAL_FLOW        1163
#define IDC_STATIC_SQVI                 1163
#define IDC_BUTTON_OK                   1164
#define IDC_CHECK_TOT_MASS              1164
#define IDC_CHECK_OIL_MASS              1165
#define IDC_STATIC_EDGE_CONC            1165
#define IDC_CHECK_WATER_CUM             1166
#define IDC_RADIO_LOW                   1166
#define IDC_CHECK_WATER_CONC            1167
#define IDC_RADIO_HIGH                  1167
#define IDC_CHECK_MADSO                 1167
#define IDC_CHECK_OIL_CONC              1168
#define IDC_CHECK_OIL_CUM               1169
#define IDC_CHECK_WATER_PEN             1170
#define IDC_STATIC_MUT_ADS1             1170
#define IDC_CHECK_OIL_PEN               1171
#define IDC_STATIC_MUT_ADS2             1171
#define IDC_STATIC_HEIGHT               1172
#define IDC_EDIT_ADS1                   1172
#define IDC_CHECK_WATERCUT2             1172
#define IDC_EDIT_NEW_SWI                1173
#define IDC_EDIT_NEW_SRO                1174
#define IDC_EDIT_CA_CONC                1175
#define IDC_EDIT_ADS2                   1175
#define IDC_EDIT_NA_CONC                1176
#define IDC_RADIO_FREU                  1176
#define IDC_RADIO_FREUNDLICH            1177
#define IDC_RADIO_LANG                  1177
#define IDC_RADIO_LANGMUIR              1178
#define IDC_RADIO_TABLE                 1178
#define IDC_EDIT_LOWADS1                1179
#define IDC_EDIT_TABLE                  1179
#define IDC_EDIT_LOWADS2                1180
#define IDC_EDIT_MAX_ADS                1180
#define IDC_EDIT_HIGHADS1               1181
#define IDC_CHECK_IRR                   1181
#define IDC_EDIT_HIGHADS2               1182
#define IDC_KH                          1182
#define IDC_STATIC_MAX_ADS              1182
#define IDC_STATIC_LOWADS1              1183
#define IDC_LAYPRES                     1183
#define IDC_PIDF2                       1183
#define IDC_STATIC_LOWADS2              1184
#define IDC_PIDF                        1184
#define IDC_LAYPRES2                    1184
#define IDC_STATIC_HIGHADS1             1185
#define IDC_STATIC_HIGHADS2             1186
#define IDC_EDIT_LOW_NA                 1187
#define IDC_BUTTON_ALLLAYERS            1187
#define IDC_EDIT_HIGH_NA                1188
#define IDC_CHECK_ALLLAYERS             1188
#define IDC_RADIO_BAR                   1189
#define IDC_BUTTON_OPT                  1189
#define IDC_RADIO_PSI                   1190
#define IDC_STATIC_FILENAME             1190
#define IDC_BUTTON_PHREEQC              1190
#define IDC_STATIC_OPT                  1191
#define IDC_CHECK_PRESS                 1193
#define IDC_CHECK_GRAPHS                1194
#define IDC_STATIC_IRREDUCIBLE          1195
#define IDC_STATIC_NEWSWI               1196
#define IDC_STATIC_NEWSRO               1197
#define IDC_CHECK_MODADD                1198
#define IDC_BUTTON_GA                   1202
#define IDC_BUTTON_RCGA                 1203
#define IDC_BUTTON_HC                   1204
#define IDC_BUTTON_PSO                  1205
#define IDC_BUTTON_PSO_TEST             1206
#define IDC_RADIO_HC                    1207
#define IDC_RADIO_PSO                   1208
#define IDC_RADIO_RCGA                  1209
#define IDC_RADIO_SGA                   1210
#define IDC_STATIC_POPULATION           1211
#define IDC_STATIC_GENERATIONS          1212
#define IDC_EDIT_POPULATION             1213
#define IDC_RADIO_STANDARD              1214
#define IDC_RADIO_NATLOG                1215
#define IDC_STATIC_GENERATIONS2         1216
#define IDC_STATIC_KMAX                 1217
#define IDC_EDIT_KMAX                   1218
#define IDC_CHECK_INIT                  1219
#define IDC_STATIC_KMAX2                1219
#define IDC_BUTTON_ISOFITTING           1220
#define IDC_STATIC_KMAX4                1220
#define IDC_STATIC_NMAX                 1221
#define IDC_EDIT_NMAX                   1222
#define IDC_EDIT_INIT_HC                1223
#define IDC_PROGRESS1                   1224
#define IDC_STATIC_KMAX3                1225
#define IDC_STATIC_VOL_INJ              1225
#define IDC_EDIT_RMAX                   1226
#define IDC_STATIC_VOL_PROD             1226
#define IDC_BUTTON_UPDATE               1227
#define IDC_EDIT_RMAX2                  1227
#define IDC_STATIC_KMIN                 1229
#define IDC_STATIC_ISO_GRAPH            1229
#define IDC_EDIT_KMIN                   1230
#define IDC_STATIC_NMIN                 1231
#define IDC_STATIC_KMIN4                1231
#define IDC_EDIT_NMIN                   1232
#define IDC_STATIC_RMIN                 1233
#define IDC_EDIT_RMIN                   1234
#define IDC_STATIC_INIT_HC              1235
#define IDC_EDIT_R_ORIG                 1235
#define IDC_STATIC_ISOGRAPH2            1236
#define IDC_EDIT_R_UP                   1236
#define IDC_CHECK1                      1237
#define IDC_CHECK_FIX_LIMITS            1237
#define IDC_EDIT_RMIN2                  1237
#define IDC_LIST1                       1238
#define IDC_STATIC_KMIN2                1238
#define IDC_LIST_ISOTHERMS              1239
#define IDC_STATIC_KMIN3                1239
#define IDC_BUTTON_ISO_TEST             1241
#define IDC_STATIC_GRAP_ISO             1242
#define IDC_BUTTON_ISO_TEST2            1242
#define IDC_BUTTON_MOPSO                1242
#define IDC_EDIT_YMAX                   1243
#define IDC_EDIT_XMAX                   1244
#define IDC_EDIT_YMIN                   1245
#define IDC_EDIT_XMIN                   1246
#define IDC_CHECK_YLOGSCALE             1247
#define IDC_STATIC_GRAPH_ISO_DER_SIM_CHECK 1248
#define IDC_STATIC_GRAPH_ISO_DER_CHECK  1249
#define ID_AUTOMATIC                    1250
#define IDC_STATIC_AUTO                 1251
#define IDC_EDIT_YMAX_SIM               1252
#define IDC_EDIT_XMAX_SIM               1253
#define IDC_EDIT_YMIN_SIM               1254
#define IDC_EDIT_XMIN_SIM               1255
#define IDC_CHECK_YLOG                  1256
#define ID_AUTOMATIC2                   1257
#define ID_BUTTON_VAL_ISO               1257
#define IDC_SLIDER1                     1257
#define IDC_SLIDER_SP_TS                1257
#define ID_BUTTON_SAVE_ISO              1258
#define IDC_STATIC_FRAME                1261
#define IDC_STATIC_TXT                  1262
#define IDC_EDIT_NAPHDEN                1263
#define IDC_EDIT_NAHECAP                1264
#define IDC_STATIC_NAPHDEN              1265
#define IDC_BUTTON_PAR_RUN              1265
#define IDC_BUTTON_PAR_OPT              1266
#define IDC_STATIC_OLDFILES2            1266
#define IDC_STATIC_OPTIMISATION         1267
#define IDC_BUTTON_PAR_OPT2             1268
#define IDC_BUTTON1                     1269
#define IDC_STATIC_OPTIMISATION2        1270
#define IDC_EDIT_InjHourRate            1271
#define IDC_EDIT_K_ORIG                 1272
#define IDC_EDIT_MIC                    1273
#define IDC_EDIT_N_ORIG                 1274
#define IDC_EDIT_nGen                   1275
#define IDC_EDIT_K_UP                   1276
#define IDC_EDIT_nPopSize               1277
#define IDC_EDIT_N_UP                   1278
#define IDC_EDIT_SICost                 1279
#define IDC_EDIT_K_LOW                  1280
#define IDC_EDIT_T_V                    1281
#define IDC_EDIT_N_LOW                  1282
#define IDC_STATIC_GRAPH_RESULTS        1282
#define IDC_STATIC_SI_COST              1283
#define IDC_STATIC_DESIGNS              1283
#define IDC_EDIT_R_LOW                  1284
#define IDC_STATIC_DESIGNS_HEADER       1284
#define IDC_STATIC_T_V                  1285
#define IDC_STATIC_AXIS_GRID            1285
#define IDC_EDIT_POP_SIZE               1286
#define IDC_EDIT_NUM_GEN                1287
#define IDC_STATIC_PARETO_GRAPH         1288
#define IDC_COMBO_XAXIS                 1289
#define IDC_COMBO_YAXIS                 1290
#define IDC_STATIC_XAXIS                1291
#define IDC_STATIC_YAXIS                1292
#define IDC_SCROLLBAR_VER               1293
#define IDC_SCROLLBAR_HOR               1294
#define IDC_CHECK_OPER_CONS             1294
#define IDC_EDIT_nBins                  1295
#define IDC_EDIT_SI_VOL                 1296
#define IDC_EDIT_TOT_VOL                1297
#define IDC_STATIC_TOT_VOL              1298
#define IDC_STATIC_SI_VOL               1299
#define IDC_CHECK_ONLY_SI_VOL           1300
#define IDC_BUTTON2                     1300
#define IDC_CHECK_ONLY_TOT_VOL          1301
#define IDC_BUTTON_Sec_Opt              1304
#define IDC_CHECK_FIXED_TARGET          1308
#define IDC_EDIT_BinsMT                 1309
#define IDC_EDIT_IterationsSecant       1310
#define IDC_EDIT_YMIN_ISO               1313
#define IDC_EDIT_POPULATION_SIZE        1314
#define IDC_EDIT_YMAX_ISO               1315
#define IDC_EDIT_ISO_MOVING               1316
#define ID_COPYTOCLIPBOARD_COPYTOCLIPBOARD 32771
#define ID_COPYTOCLIPBOARD              32772
#define ID_POPUP                        32773
#define ID_POPUP32774                   32774
#define ID_CONTEXTMENU_SAVEIMAGE        32775
#define ID_SAVEIMAGE                    32776
#define ID_SAVEOUTPUT                   32777
#define ID_EXPORTTABLE_EXPORTPARETOFRONT 32777
#define ID_EXPORTTABLE_EXPORTTABLE      32778
#define ID__SAVEDESIGN                  32779
#define ID__EXPORTTABLE                 32780
#define ID__EXPORTPARETOFRONT           32781
#define IDC_SQVI_ICON                   65535
#define IDC_ICON_SQVI                   65535
#define IDC_ICON_OPT                    65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1313
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
